jobs:
- job: Build_Boost
  timeoutInMinutes: 300
  pool:
    name: Azure Pipelines
    vmImage: $(VmImage)
  steps:
  - checkout: self
  - task: PowerShell@2
    displayName: 'Build Boost $(Version)'
    inputs:
      targetType: filePath
      filePath: './builders/build-boost.ps1'
      arguments: '-Version $(Version) -Platform $(Platform) -Architecture $(Architecture) -Toolset $(Toolset)'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifact: Boost $(Version)'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'boost-$(Version)-$(Platform)-$(Toolset)-$(Architecture)'